---
- name: systemd-container role
  tags:
    - systemd-container
  block:

  - ansible.builtin.import_tasks: install_apt.yml

  # mkdir /var/lib/machines
  - name: Mkdir /var/lib/machines (set correct perms)
    become: true
    ansible.builtin.file:
      path: /var/lib/machines
      mode: u=rwx,g=,o=

  # reset /etc/systemd/nspawn
  - when: systemd_container_nspawn_config_reset == true  
    name: Remove /etc/systemd/nspawn
    become: true
    ansible.builtin.file:
      path: /etc/systemd/nspawn
      state: absent

  # mkdir /etc/systemd/nspawn
  - name: Mkdir /etc/systemd/nspawn
    become: true
    ansible.builtin.file:
      path: /etc/systemd/nspawn
      state: directory
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx

  - ansible.builtin.import_tasks: config_nspawn_copy.yml
  - ansible.builtin.import_tasks: config_nspawn_sync.yml
  - ansible.builtin.import_tasks: config_nspawn_template.yml