---
- name: systemd-container role
  tags:
    - systemd-container
  block:

  # apt
  - name: Apt {{ systemd_container.apt.state }} systemd-container
    become: true
    ansible.builtin.apt:
      state: "{{ systemd_container.apt.state }}"
      name: systemd-container

  # mkdir /etc/systemd/nspawn
  - name: Mkdir /etc/systemd/nspawn
    become: true
    ansible.builtin.file:
      path: /etc/systemd/nspawn
      state: directory
      owner: root
      group: root
      mode: o=rwx,g=rx,o=rx

  # mkdir /var/lib/machines
  - name: Mkdir /var/lib/machines (set correct perms)
    become: true
    ansible.builtin.file:
      path: /var/lib/machines
      mode: o=rwx,g=,o=

  # systemd-machined.service
  - name: Start & enable systemd-machined.service
    become: true
    ansible.builtin.systemd_service:
      name: systemd-machined.service
      state: started
      enabled: true

  # systemd_container.files.cp
  - when: systemd_container.files.cp | length > 0
    block:

    # cp
    - name: Copy .nspawn files {{ systemd_container.files.cp }}
      become: true
      loop: "{{ systemd_container.files.cp }}"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/systemd/nspawn/

  # systemd_container.files.rm
  - when: systemd_container.files.rm | length > 0
    block:
    
    # rm
    - name: Remove .nspawn files {{ systemd_container.files.rm }}
      become: true
      loop: "{{ systemd_container.files.rm }}"
      ansible.builtin.file:
        path: "/etc/systemd/nspawn/{{ item }}"
        state: absent